version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    image: "jouiry/multi-nginx:latest"
    depends_on:
      - api
      - client
    restart: always
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  client:
    environment:
      - WDS_SOCKET_PORT=0
    image: "jouiry/multi-client:latest"
    mem_limit: 128m
    hostname: client
  server:
    image: "jouiry/multi-server:latest"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "jouiry/multi-worker:latest"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

